import { Component, inject, signal } from '@angular/core';
import { forkJoin } from 'rxjs';
import { SearchService } from '../../../core/services/search';
import { ToastService } from '../../../core/services/toast';

/**
 * Drag/drop or click image upload that runs AI similarity search + description.
 * The backend describe-image (OpenAI) returns a textual description; search-by-image
 * matches against product images embedded in Chroma. If no product images have been
 * embedded, matches come back empty (the description still shows).
 */
@Component({
  selector: 'app-image-search',
  template: `
    <div class="image-search-container mt-3">
      <div class="image-uploader" [class.dragover]="dragging()"
           (click)="fileInput.click()"
           (dragover)="onDragOver($event)"
           (dragleave)="onDragLeave($event)"
           (drop)="onDrop($event)">
        <input #fileInput type="file" accept="image/*" class="d-none"
               (change)="onInputChange($event)" aria-label="Upload image to search" />
        @if (previewUrl(); as url) {
          <img [src]="url" alt="Selected image preview" />
        } @else {
          <div class="text-secondary">
            <i class="bi bi-cloud-arrow-up fs-1"></i>
            <p class="mb-0">Drag &amp; drop an image here, or click to browse</p>
          </div>
        }
      </div>

      <div class="image-url-input">
        <button type="button" class="image-search-button" [disabled]="!file || loading()"
                (click)="runSearch()">
          @if (loading()) {
            <span class="spinner-border spinner-border-sm me-2"></span>
          }
          Search by image
        </button>
      </div>

      @if (loading()) {
        <p class="text-muted mt-2 small">Analyzing image…</p>
      }

      @if (description()) {
        <div class="hero-image-description-box mx-auto mt-3 text-start">
          <div class="hero-image-description-title">Image description</div>
          <div class="hero-image-description-text">{{ description() }}</div>
        </div>
      }

      @if (infoMessage()) {
        <p class="text-muted mt-2 small">{{ infoMessage() }}</p>
      }
      @if (errorMessage()) {
        <p class="text-danger mt-2 small">{{ errorMessage() }}</p>
      }
    </div>
  `,
  styles: [`
    .image-uploader.dragover {
      border-color: var(--accent);
      background-color: #e9eef5;
    }
  `],
})
export class ImageSearch {
  private readonly search = inject(SearchService);
  private readonly toast = inject(ToastService);

  protected file: File | null = null;
  protected readonly previewUrl = signal<string | null>(null);
  protected readonly loading = signal(false);
  protected readonly errorMessage = signal('');
  protected readonly infoMessage = signal('');
  protected readonly dragging = signal(false);
  protected readonly description = this.search.imageDescription;

  onInputChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    this.acceptFile(input.files?.[0] ?? null);
  }

  onDragOver(event: DragEvent): void {
    event.preventDefault();
    this.dragging.set(true);
  }

  onDragLeave(event: DragEvent): void {
    event.preventDefault();
    this.dragging.set(false);
  }

  onDrop(event: DragEvent): void {
    event.preventDefault();
    this.dragging.set(false);
    const dropped = event.dataTransfer?.files?.[0] ?? null;
    this.acceptFile(dropped);
  }

  /** Stores the chosen file, shows a preview, and immediately runs the search. */
  private acceptFile(file: File | null): void {
    if (!file || !file.type.startsWith('image/')) {
      return;
    }
    this.file = file;
    this.errorMessage.set('');
    this.infoMessage.set('');
    this.previewUrl.set(URL.createObjectURL(file));
    this.runSearch();
  }

  runSearch(): void {
    if (!this.file) {
      return;
    }
    this.loading.set(true);
    this.errorMessage.set('');
    this.infoMessage.set('');

    forkJoin({
      results: this.search.searchByImage(this.file),
      description: this.search.describeImage(this.file),
    }).subscribe({
      next: ({ results, description }) => {
        this.search.imageSearchResults.set(results);
        this.search.imageDescription.set(description);
        this.loading.set(false);
        if (results.length > 0) {
          this.toast.success(`Found ${results.length} matching product(s).`);
        } else {
          this.infoMessage.set(
            'No visually similar products found. (Matches require product images to be ' +
              'uploaded and indexed; the description above is still generated by AI.)',
          );
        }
      },
      error: () => {
        this.loading.set(false);
        this.errorMessage.set(
          'AI image search is unavailable (the backend needs OpenAI + Chroma reachable).',
        );
      },
    });
  }
}
